image: node:18

stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  script:
    - echo "VITE_SUITMEDIA_API_URL=$SUITMEDIA_API_URL" >> .env
    - npm install

build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy_project:
  stage: deploy
  only:
    - main
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - echo "Starting FTP upload..."
    - lftp -c "
      open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
      mirror -R -e dist/ /$FTP_TARGET_DIR;
      "